// oxlint-disable-next-line typescript/ban-ts-comment
// @ts-ignore This module is generated by `opennextjs-cloudflare build` before Wrangler bundles this worker.
import openNextWorker from "../../.open-next/worker.js"
import { PedalSession } from "./pedal-session-worker"
import { createPedalSignalRequest } from "./signal-route"

/* oxlint-disable typescript/method-signature-style */
interface PedalSessionsBinding {
  getByName(name: string): {
    fetch(request: Request): Promise<Response>
  }
}

interface PedalWorkerEnv {
  PEDAL_SESSIONS: PedalSessionsBinding
}

interface PedalExecutionContext {
  waitUntil(promise: Promise<unknown>): void
}

interface OpenNextWorker {
  fetch: (
    request: Request,
    env: PedalWorkerEnv,
    context: PedalExecutionContext,
  ) => Promise<Response>
}

const sessionIdPattern = /^[A-Za-z0-9_-]{22,128}$/

function getSignalSessionId(pathname: string) {
  const match = /^\/api\/pedal\/sessions\/([^/]+)\/signal$/u.exec(pathname)
  return match && sessionIdPattern.test(match[1]) ? match[1] : undefined
}

export { PedalSession }

const openNextHandler: OpenNextWorker = openNextWorker

export default {
  async fetch(request: Request, env: PedalWorkerEnv, context: PedalExecutionContext) {
    const sessionId = getSignalSessionId(new URL(request.url).pathname)
    if (sessionId) {
      return env.PEDAL_SESSIONS.getByName(sessionId).fetch(createPedalSignalRequest(request))
    }
    return openNextHandler.fetch(request, env, context)
  },
}
